import RwRegionReport from "./RwRegionReport";
import { props } from "@webflow/data-types";
import { declareComponent } from "@webflow/react";

export default declareComponent(RwRegionReport, {
  name: "RW Region Report",
  description:
    "Full electrification report for one district/region (v2 layout: banner, hero, headline stats, cumulative graph, jump-navs, economics, emissions & jobs, bills, solar, EV, heat pump, hot water, induction) with per-location charts for all 82 locations built in. Blank slug = auto from the page URL. The 'Local stories' and 'Community group' jump cards scroll to elements with id=\"stories\" and id=\"community\" — set those ids on the sections you build around this component.",
  group: "Region Reports",
  options: { ssr: false },
  props: {
    districtSlug: props.Text({
      name: "District slug (blank = auto from URL)",
      defaultValue: "",
      group: "Content",
    }),
    /* BEGIN generated text props - build_editable_text.py */
    heroAndOpportunityHeading: props.Text({ name: "Heading · Electrifying location", defaultValue: "Electrifying {{location}}", group: "Hero and opportunity" }),
    heroAndOpportunityPara1: props.Text({ name: "Paragraph 1 · A pathway to savings for households,…", defaultValue: "A pathway to savings for households, economic growth for the community, reduced emissions and greater resilience.", group: "Hero and opportunity" }),
    heroAndOpportunityPara2: props.Text({ name: "Paragraph 2 · location has crossed the…", defaultValue: "{{location}} has <strong>crossed the electrification tipping point</strong> where homes can save money and reduce their emissions by going electric.", group: "Hero and opportunity" }),
    heroAndOpportunityPara3: props.Text({ name: "Paragraph 3 · The technology is proven, the…", defaultValue: "The technology is proven, the economics stack up, and the transition is already underway. But there are still plenty of households paying more than they need to by running on fossil fuels.", group: "Hero and opportunity" }),
    heroAndOpportunityHeading2: props.Text({ name: "Heading 2 · The opportunity for location", defaultValue: "The opportunity for {{location}}", group: "Hero and opportunity" }),
    heroAndOpportunityPara4: props.Text({ name: "Paragraph 4 · *upgrading appliances to electric and…", defaultValue: "*upgrading appliances to electric and adding solar and batteries to 80% of homes", group: "Hero and opportunity" }),
    heroAndOpportunityPara5: props.Text({ name: "Paragraph 5 · See what my household could save", defaultValue: "<a href=\"#bills\">See what my household could save &rarr;</a>", group: "Hero and opportunity" }),
    heroAndOpportunityHeading3: props.Text({ name: "Heading 3 · location homes could cumulatively…", defaultValue: "{{location}} homes could cumulatively save a net {{cumulative_savings}} between 2026 and 2040", group: "Hero and opportunity" }),
    economicsHeading: props.Text({ name: "Heading · Economics", defaultValue: "Economics", group: "Economics" }),
    economicsPara1: props.Text({ name: "Paragraph 1 · That's fossil spend annual spent each…", defaultValue: "That's <strong>{{fossil_spend_annual}} spent each year</strong> on fossil fuels by just households in {{location}}. Most of these fossil fuels are imported, meaning this money leaves the local economy. Plus, history shows fossil fuel costs are volatile, with <strong>prices rising faster than the rate of inflation</strong>.", group: "Economics" }),
    economicsPara2: props.Text({ name: "Paragraph 2 · If every location home were to…", defaultValue: "If every {{location}} home were to electrify all appliances and vehicles, with 80% also adopting rooftop solar and home batteries, household energy costs would drop significantly. That's <strong>{{elec_savings_daily}} saved per day</strong>, and meaningful cost of living relief for {{location}} households.", group: "Economics" }),
    emissionsAndJobsHeading: props.Text({ name: "Heading · Emissions and jobs", defaultValue: "Emissions and jobs", group: "Emissions and jobs" }),
    emissionsAndJobsPara1: props.Text({ name: "Paragraph 1 · Electrifying location's homes will…", defaultValue: "Electrifying {{location}}'s homes will result in a significant reduction in emissions. That's the equivalent of <strong>{{equiv_flights}} one-way flights</strong> per passenger from Auckland to Queenstown.", group: "Emissions and jobs" }),
    emissionsAndJobsPara2: props.Text({ name: "Paragraph 2 · New local jobs, driven by additional…", defaultValue: "<strong>New local jobs</strong>, driven by additional installation labour and the savings flowing through the community.", group: "Emissions and jobs" }),
    billsHeading: props.Text({ name: "Heading · Bills", defaultValue: "Bills", group: "Bills" }),
    billsPara1: props.Text({ name: "Paragraph 1 · An average location home using gas…", defaultValue: "An average {{location}} home using gas appliances and petrol vehicles is losing out on around <strong>{{bill_savings}} in savings</strong> on its energy bills every year compared to a home with electrified appliances and vehicles plus a solar and battery system. Plus energy spending is spread across multiple fuels, each with its own bill, its own price fluctuations, and its own supplier.", group: "Bills" }),
    billsPara2: props.Text({ name: "Paragraph 2 · With upfront costs and loan…", defaultValue: "With upfront costs and loan repayments included, an all-electric {{location}} home is still <strong>{{bills_net_savings}} net better off per year</strong>, and a net <strong>{{bills_net_15yr}} better off over 15 years</strong>. An electric home consolidates their energy into a single source &mdash; electricity &mdash; meaning <strong>lower bills and far greater control</strong>.", group: "Bills" }),
    solarAndBatteriesHeading: props.Text({ name: "Heading · Solar and batteries", defaultValue: "Solar and batteries", group: "Solar and batteries" }),
    solarAndBatteriesPara1: props.Text({ name: "Paragraph 1 · Solar offers strong payback for…", defaultValue: "Solar offers strong payback for {{location}} homes, even in shaded areas, while improving energy independence.", group: "Solar and batteries" }),
    solarAndBatteriesPara2: props.Text({ name: "Paragraph 2 · With solar, the household is paying…", defaultValue: "With solar, the household is paying an <strong>effective electricity price of {{solar_effective_rate}}</strong> (financed at {{solar_finance_rate}}), compared to the grid rate of <strong>{{grid_rate}}</strong> (excludes fixed cost).", group: "Solar and batteries" }),
    solarAndBatteriesPara3: props.Text({ name: "Paragraph 3 · Solar panels are expected to last…", defaultValue: "Solar panels are expected to <strong>last {{solar_panel_life}} years</strong>, with warranties of a similar length, meaning the system well outlasts any loan used to finance it. And a battery adds resilience, <strong>keeping essential appliances running during outages</strong>.", group: "Solar and batteries" }),
    electricVehicleHeading: props.Text({ name: "Heading · Electric vehicle", defaultValue: "Electric vehicle", group: "Electric vehicle" }),
    electricVehiclePara1: props.Text({ name: "Paragraph 1 · EVs are far cheaper to run, require…", defaultValue: "EVs are <strong>far cheaper to run</strong>, require little maintenance and aren't exposed to volatile global fuel prices. Plus they're quiet, comfortable and fun to drive! Switching from a petrol to an electric medium SUV <strong>saves around {{ev_annual_savings}} every year</strong>, including road user charges. Diesel ute drivers save even more at <strong>{{ev_ute_savings}} net over 15 years</strong>, or {{ev_ute_annual_savings}} every year. Households in {{location}} currently spend <strong>{{pump_spend_daily}} at the pump every day</strong>.", group: "Electric vehicle" }),
    electricVehiclePara2: props.Text({ name: "Paragraph 2 · location drivers cover an average of…", defaultValue: "{{location}} drivers cover an average of <strong>{{driving_weekly_km}} per week</strong>: well within the range of a modern EV. And charging is easy. 80% of EV owners do more than half their charging at home. 60% trickle charge using a standard three-pin plug. Charging at home using grid electricity costs <strong>effectively half what you'd spend on petrol or diesel</strong>, and for those with rooftop solar, the savings are even greater. And for when you do need to charge on the go, public chargers are available at least every 75km on 97% of New Zealand highways. Savings assume a driving distance of {{driving_annual_km}} per year &mdash; for drivers exceeding this, the savings will be greater.", group: "Electric vehicle" }),
    heatPumpHeading: props.Text({ name: "Heading · Heat pump", defaultValue: "Heat pump", group: "Heat pump" }),
    heatPumpPara1: props.Text({ name: "Paragraph 1 · Heat pumps use around heatpump energy…", defaultValue: "Heat pumps use around <strong>{{heatpump_energy_pct}} less energy</strong> than gas heaters to deliver the same warmth, and, unlike gas, they cool in summer too. Switching from {{heatpump_switch_from}} to a heat pump <strong>saves {{heatpump_15yr_savings}} on bills over 15 years</strong> (around {{heatpump_annual_savings}} every year) and {{heatpump_lifetime_savings}} over the lifetime including upfront costs. {{heater_breakdown}} Whatever the fuel type, going electric brings significant savings, and the comfort upgrade is immediate.", group: "Heat pump" }),
    hotWaterHeatPumpHeading: props.Text({ name: "Heading · Hot water heat pump", defaultValue: "Hot water heat pump", group: "Hot water heat pump" }),
    hotWaterHeatPumpPara1: props.Text({ name: "Paragraph 1 · Hot water heat pumps have a higher…", defaultValue: "Hot water heat pumps have a higher upfront cost, but <strong>deliver the lowest ongoing energy bills</strong> of any water heating option. In {{location}}, switching from {{water_switch_from}} to a hot water heat pump <strong>saves {{water_15yr_savings}} on bills over 15 years</strong>, or {{water_lifetime_savings}} over the lifetime including upfront costs. {{water_breakdown}}", group: "Hot water heat pump" }),
    hotWaterHeatPumpPara2: props.Text({ name: "Paragraph 2 · Water heating makes up around water…", defaultValue: "Water heating makes up around <strong>{{water_energy_pct}} of an average home's energy load</strong> &mdash; making it one of the highest-impact switches a household can make. Hot water heat pumps can also act as a 'thermal battery' where you time it to heat water when electricity is cheapest, or when your solar panels are generating.", group: "Hot water heat pump" }),
    inductionCooktopHeading: props.Text({ name: "Heading · Induction cooktop", defaultValue: "Induction cooktop", group: "Induction cooktop" }),
    inductionCooktopPara1: props.Text({ name: "Paragraph 1 · Cooking doesn't use a lot of energy…", defaultValue: "Cooking doesn't use a lot of energy but electric cooking is <strong>lower cost (and much lower emissions)</strong> than cooking with gas. Induction is more expensive upfront than resistive electric cooking, but offers lower ongoing bills. {{cooktop_breakdown}}", group: "Induction cooktop" }),
    inductionCooktopPara2: props.Text({ name: "Paragraph 2 · But the most compelling case for…", defaultValue: "But the most compelling case for induction might be <strong>health</strong>. Gas cooking releases nitrogen dioxide and other pollutants into the home, linked nationally to <strong>200+ premature deaths, 3,200+ child asthma cases, and $3.3 billion</strong> in productivity and health costs every year.", group: "Induction cooktop" }),
    /* END generated text props */
  },
});
