"use client";

// Simple (link-out) footer for the region report: one card with the
// per-location PDF download button and the national Electric Homes & Vehicles
// Report button. The PDF link is derived from the page slug (same hosted set
// as RwRegionFooter) unless an explicit URL is given.
import React, { useEffect, useState } from "react";
import SimpleSection from "./simpleSection";
import { resolveSlug, getDistrict } from "./reportSections";
import { META } from "./districtData";

interface LinkValue {
  href: string;
  target?: string;
}

/** Webflow's Link prop yields href "#" when left empty in the props panel -
 *  treat that (and blank) as "not set" so auto-derivation can kick in. */
function linkHref(v?: LinkValue): string {
  const h = (v?.href || "").trim();
  return h && h !== "#" ? h : "";
}

/** Hosted per-location A4 PDFs - regenerated by the rewiring-district-pages
 *  pipeline (regen_all_pdfs.py) and shipped with every preview deploy. Keep in
 *  step with PDF_BASE in RwRegionFooter. */
const PDF_BASE = "https://regional-reports.pages.dev/pdf/electrifying-";
const NATIONAL_REPORT_URL = "https://pages.rewiring.nz/electric-homes-and-vehicles";

export interface RwRegionFooterSimpleProps {
  /** District/region slug override; blank = auto from the page URL. */
  districtSlug?: string;
  heading?: string;
  body?: string;
  /** "{location}" is replaced with the report's location name. */
  pdfButtonLabel?: string;
  /** Explicit PDF link; blank = the hosted PDF for the page's slug (no button when none is hosted). */
  pdfUrl?: LinkValue;
  buttonLabel?: string;
  reportUrl?: LinkValue;
  bgColor?: string;
  cardColor?: string;
  inkColor?: string;
  accentColor?: string;
  goldColor?: string;
}

export default function RwRegionFooterSimple({
  districtSlug = "",
  heading = "Take this report with you",
  body = "Download a shareable PDF of this report for council meetings, community groups or your neighbours. Unless otherwise stated, data in this report is drawn from Rewiring Aotearoa's independent, peer reviewed modelling - dig into the numbers behind these figures in the Electric Homes & Vehicles Report 2026.",
  pdfButtonLabel = "Download the {location} report (PDF)",
  pdfUrl,
  buttonLabel = "Electric Homes & Vehicles Report",
  reportUrl,
  bgColor = "#fdf7ea",
  cardColor = "#ffffff",
  inkColor = "#1a3c3c",
  accentColor = "#234e4c",
  goldColor = "#f5b731",
}: RwRegionFooterSimpleProps) {
  // resolveSlug reads window.location, so SSR renders without the PDF button and
  // hydration adds it once the slug is known (same pattern as RwRegionFooter).
  const [auto, setAuto] = useState<{ href: string; loc: string }>({ href: "", loc: "" });
  useEffect(() => {
    const slug = resolveSlug(districtSlug);
    const hosted = META.some((m) => m.slug === slug);
    setAuto({ href: hosted ? PDF_BASE + slug + ".pdf" : "", loc: getDistrict(slug)?.fields?.location || "" });
  }, [districtSlug]);

  const pdfHref = linkHref(pdfUrl) || auto.href;
  const pdfLabel = pdfHref ? pdfButtonLabel.replace("{location}", auto.loc || "this").replace(/\s+/g, " ").trim() : "";

  return (
    <SimpleSection
      heading={heading}
      body={body}
      buttonLabel={pdfLabel}
      href={pdfHref}
      icon="download"
      secondaryLabel={buttonLabel}
      secondaryHref={linkHref(reportUrl) || NATIONAL_REPORT_URL}
      secondaryIcon="book"
      bgColor={bgColor}
      cardColor={cardColor}
      inkColor={inkColor}
      accentColor={accentColor}
      goldColor={goldColor}
    />
  );
}
